# Starter pipeline
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud (Highbyte)'
    organization: 'highbyte'
    scannerMode: 'MSBuild'
    projectKey: 'highbyte_SonarqubeMSTeamsBridge'
    projectName: 'SonarqubeMSTeamsBridge'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    workingDirectory: 'src'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--no-restore --collect "Code coverage"'
    workingDirectory: 'src'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
